version: "3"
services:

  app:
    build: .
    container_name: app
    depends_on: 
      - postgres
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    networks:
      - boilerplate-net
  
  postgres:
    image: postgres:15-alpine
    container_name: boilerplate-postgresql
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=boilerplate
    ports:
      - "5435:5432"
    networks:
      - boilerplate-net

  server:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - app
      - postgres
    volumes:
      - ./:/var/www/html
      - ./server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - boilerplate-net
  
networks:
  boilerplate-net:

volumes:
  postgres-vol:
